SELECT
    _ID AS post_id,
    _POSTTYPEID AS post_type_id,
    _CREATIONDATE AS creation_date,
    _SCORE AS score,
    _VIEWCOUNT AS view_count,
    _BODY AS body,
    _OWNERUSERID AS owner_user_id,
    _LASTEDITORUSERID AS last_editor_user_id,
    _LASTEDITDATE AS last_edit_date,
    _LASTACTIVITYDATE AS last_activity_date,
    _TITLE AS title,
    _TAGS AS tags,
    _ANSWERCOUNT AS answer_count,
    _COMMENTCOUNT AS comment_count,
    _CONTENTLICENSE AS content_license,
    _ACCEPTEDANSWERID AS accepted_answer_id,
    _FAVORITECOUNT AS favorite_count,
    _OWNERDISPLAYNAME AS owner_display_name,
    _CLOSEDDATE AS closed_date,
    _COMMUNITYOWNEDDATE AS community_owned_date,
    _PARENTID AS parent_id,
    _LASTEDITORDISPLAYNAME AS last_editor_display_name
--FROM SNOWFLAKE_FINAL_PROJECT.PUBLIC.POSTS
FROM {{ source('public', 'posts') }}
